- name: playbook to deploy the bookstore application
  hosts: all
  become: true

  tasks:
  - name: deploy the application in RHEL instances
    block:
    - name: ensure nginx is at latest version
      package:
        name: nginx
        state: latest
    - name: ensure required php dependencies installed
      package:
        name:
        - php8.1.x86_64
        - php8.1-gd.x86_64
        - php8.1-soap.x86_64
        - php8.1-intl.x86_64
        - php8.1-mysqlnd.x86_64
        - php8.1-pdo.x86_64
        - php8.1-fpm.x86_64
        - php8.1-odbc.x86_64
        - php8.1-common.x86_64
        - php8.1-xml.x86_64
    - name: restart the php-fpm service
      service:
        name: php-fpm
        state: restarted
    - name: remove the previous nginx path if present
      file:
        path: /usr/share/nginx/bookstore
        state: absent
      ignore_errors: true
    - name: copy the new application files
      copy:
        src: /home/ec2-user/bookstore
        dest: /usr/share/nginx/bookstore
        owner: root
        group: root
        mode: 755
    - name: copy the nginx config file
      copy:
        src: /home/ec2-user/nginx_rhel.conf
        dest: /etc/nginx/nginx.conf
    - name: copy the nginx default config file
      copy:
        src: /home/ec2-user/bookstore/nginx.conf.default
        dest: /etc/nginx/nginx.conf.default
    - name: restart the nginx service
      service:
        name: nginx
        state: restarted
    when: ansible_distribution == "Amazon"

  - name: deploy the application in RHEL instances
    block:
    - name: ensure nginx is at latest version
      package:
        name: nginx
        state: latest
    - name: ensure required php dependencies installed
      package:
        name:
        - php8.1-fpm
        - php-mysql
    - name: restart the php-fpm service
      service:
        name: php8.1-fpm
        state: restarted
    - name: remove the previous nginx path if present
      file:
        path: /var/www/html/bookstore
        state: absent
      ignore_errors: true
    - name: copy the new application files
      copy:
        src: /home/ec2-user/bookstore
        dest: /var/www/html/bookstore
        owner: root
        group: root
        mode: 755
    - name: copy the nginx config file
      copy:
        src: /home/ec2-user/nginx_ubuntu.conf
        dest: /etc/nginx/sites-available/default
    - name: create the hard link for the config file
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: restart the nginx service
      service:
        name: nginx
        state: restarted
    when: ansible_distribution == "Ubuntu"
